import React, { useRef } from 'react';
import { Share2, Copy, Check, Camera, X } from 'lucide-react';
import { Shield, Swords, Crown, Skull, Star, Zap } from 'lucide-react';

const ICONS = {
    shield: Shield,
    swords: Swords,
    crown: Crown,
    skull: Skull,
    star: Star,
    zap: Zap,
};

export function PublishedView({
    teamA,
    teamB,
    colorA,
    colorB,
    nameA,
    nameB,
    iconA,
    iconB,
    instructions,
    onClose
}) {
    const IconA = ICONS[iconA] || Shield;
    const IconB = ICONS[iconB] || Swords;

    return (
        <div className="published-overlay">
            <div className="published-card">
                <button className="close-btn" onClick={onClose}>
                    <X size={24} />
                </button>

                <div className="published-content">
                    <header className="match-header">
                        <h2>⚽ Match Day Squad ⚽</h2>
                        {instructions && <p className="match-instructions">{instructions}</p>}
                    </header>

                    <div className="teams-container">
                        {/* Team A */}
                        <div className="team-column">
                            <div className="team-title" style={{ color: colorA }}>
                                <IconA size={24} />
                                <h3>{nameA}</h3>
                            </div>
                            <ul className="team-list">
                                {teamA.map((p, i) => (
                                    <li key={p.id}>
                                        <span className="player-number">{i + 1}.</span> {p.name}
                                    </li>
                                ))}
                                {teamA.length === 0 && <li className="empty-msg">No players</li>}
                            </ul>
                        </div>

                        <div className="vs-divider">VS</div>

                        {/* Team B */}
                        <div className="team-column">
                            <div className="team-title" style={{ color: colorB }}>
                                <IconB size={24} />
                                <h3>{nameB}</h3>
                            </div>
                            <ul className="team-list">
                                {teamB.map((p, i) => (
                                    <li key={p.id}>
                                        <span className="player-number">{i + 1}.</span> {p.name}
                                    </li>
                                ))}
                                {teamB.length === 0 && <li className="empty-msg">No players</li>}
                            </ul>
                        </div>
                    </div>

                    <div className="watermark">Generated by Soccer Team Manager</div>
                </div>
            </div>
        </div>
    );
}
